version: "3.8"
services:
  mysql-primary:
    image: mysql:8.0
    container_name: mysql-transaction
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
