-- 1
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT @@SESSION.transaction_isolation;

-- 3
START TRANSACTION;

-- 5
SELECT * FROM hello.MEMBER WHERE id = 4; -- HELLO4

-- 7
UPDATE hello.MEMBER SET name = 'TX1TX1' WHERE id = 4;

-- 9
SELECT * FROM hello.MEMBER WHERE id=4;

-- 11
COMMIT;
