-- 1
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT @@SESSION.transaction_isolation;

-- 3
START TRANSACTION;

-- 5
SELECT * FROM hello.MEMBER WHERE id = 4; -- HELLO4

-- 7
UPDATE hello.MEMBER SET name = 'TX1TX1' WHERE id = 4;

-- 8
SELECT * FROM hello.MEMBER WHERE id = 4; -- TX1TX1

-- 9
COMMIT;
