spring:
  application:
    name: hello-database
  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/hello-database
      username: user
      password: password
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3308/hello-database
      username: user
      password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
