-- 5
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT @@SESSION.transaction_isolation;

-- 6
START TRANSACTION;

-- 7
SELECT * FROM hello.MEMBER WHERE id = 1; -- UPDATE1

-- 10
COMMIT;
