-- 1
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT @@SESSION.transaction_isolation;

-- 3
START TRANSACTION;

-- 5
SELECT COUNT(*) FROM hello.DOCTOR WHERE on_call = TRUE; -- 2

-- 7
UPDATE hello.DOCTOR SET on_call = FALSE WHERE id = 1;

-- 8
COMMIT;
