-- 2
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT @@SESSION.transaction_isolation;

-- 4
START TRANSACTION;

-- 6
SELECT COUNT(*) FROM hello.DOCTOR WHERE on_call = TRUE; -- 2

-- 9
UPDATE hello.DOCTOR SET on_call = TRUE WHERE id = 2;

-- 10
COMMIT;
